spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ0dhOGxZTXMyc2Q4OVJZNWoKdUlLM2lTL3ZEU3JqTmVuUm1oZGk3ZlJsVVhTaFJBTkNBQVJENzVWZkNZWmZwdkh6VFBNRE5DTVZxQUd6SEJwMgpxaWdhQzFxeWFaeVdHQTVFSVcvb3cySzFHcTR1a1BlcUtBYkZUMjdUWDJDcVk1a3NBWGZDQktaNAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNSekNDQWV5Z0F3SUJBZ0lRWnlUNS9NWk1OeWUveUlXWkc0ZzAxREFLQmdncWhrak9QUVFEQWpDQmlURWUKTUJ3R0ExVUVDaE1WYld0alpYSjBJR1JsZG1Wc2IzQnRaVzUwSUVOQk1TOHdMUVlEVlFRTERDWndZWFZzWW1GMQpaR2x1YjNSQVRXRmpMbXh2WTJGc0lDaFFZWFZzSUVKaGRXUnBibTkwS1RFMk1EUUdBMVVFQXd3dGJXdGpaWEowCklIQmhkV3hpWVhWa2FXNXZkRUJOWVdNdWJHOWpZV3dnS0ZCaGRXd2dRbUYxWkdsdWIzUXBNQjRYRFRJMk1EUXgKTlRBNU1UY3lObG9YRFRJNE1EY3hOVEE1TVRjeU5sb3dXakVuTUNVR0ExVUVDaE1lYld0alpYSjBJR1JsZG1WcwpiM0J0Wlc1MElHTmxjblJwWm1sallYUmxNUzh3TFFZRFZRUUxEQ1p3WVhWc1ltRjFaR2x1YjNSQVRXRmpMbXh2ClkyRnNJQ2hRWVhWc0lFSmhkV1JwYm05MEtUQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFUHYKbFY4SmhsK204Zk5NOHdNMEl4V29BYk1jR25hcUtCb0xXckpwbkpZWURrUWhiK2pEWXJVYXJpNlE5Nm9vQnNWUApidE5mWUtwam1Td0JkOElFcG5palpEQmlNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyCkJnRUZCUWNEQVRBZkJnTlZIU01FR0RBV2dCU3R0RkVMallnTFRUR290Z2Y1YnpjTXZjc3VnVEFhQmdOVkhSRUUKRXpBUmdnOXNiMk5oYkM0d2VHUmlaUzVrWlhZd0NnWUlLb1pJemowRUF3SURTUUF3UmdJaEFMTkxBMmo0bWQ4cQpSMkM4cFh4ZzJiSTBoM0ZReXQvZzJ2NTBlT3FoMkNnTkFpRUFtRkx3RFhycUJYQ1J1djcwdW5ENFcrTzd2R0hnCkttanJiMnEwTWJFcGExUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
          trustore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXRENDQWY2Z0F3SUJBZ0lSQUtkaXJtNWFiYVdBaVVVZkJvZTM4RkV3Q2dZSUtvWkl6ajBFQXdJd2dZa3gKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURXZNQzBHQTFVRUN3d21jR0YxYkdKaApkV1JwYm05MFFFMWhZeTVzYjJOaGJDQW9VR0YxYkNCQ1lYVmthVzV2ZENreE5qQTBCZ05WQkFNTUxXMXJZMlZ5CmRDQndZWFZzWW1GMVpHbHViM1JBVFdGakxteHZZMkZzSUNoUVlYVnNJRUpoZFdScGJtOTBLVEFlRncweU5qQTAKTVRVd09URTJNemhhRncwek5qQTBNVFV3T1RFMk16aGFNSUdKTVI0d0hBWURWUVFLRXhWdGEyTmxjblFnWkdWMgpaV3h2Y0cxbGJuUWdRMEV4THpBdEJnTlZCQXNNSm5CaGRXeGlZWFZrYVc1dmRFQk5ZV011Ykc5allXd2dLRkJoCmRXd2dRbUYxWkdsdWIzUXBNVFl3TkFZRFZRUUREQzF0YTJObGNuUWdjR0YxYkdKaGRXUnBibTkwUUUxaFl5NXMKYjJOaGJDQW9VR0YxYkNCQ1lYVmthVzV2ZENrd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRZgpRcU5vejZ5QjdKcHZwNnJlQmxFQlV4a2l4SXJrdmpLajA2UXJVQ1ZyVVpFTlMxSVU3RGF3ZnBRN1NTM2NhNDU2CmJlSGwrclZxc1hmdCtLVUxtaFY4bzBVd1F6QU9CZ05WSFE4QkFmOEVCQU1DQWdRd0VnWURWUjBUQVFIL0JBZ3cKQmdFQi93SUJBREFkQmdOVkhRNEVGZ1FVcmJSUkM0MklDMDB4cUxZSCtXODNETDNMTG9Fd0NnWUlLb1pJemowRQpBd0lEU0FBd1JRSWhBTkROY1d2WERvTFJGSm5pSUZ1KzVjNThTbXcxMWVLcExJV0wvQUJLbHJuMUFpQVR3VHpnCkxYTmlocElGSjkvek5yU1NhQW5pTktGRWdTN2Z3VURpY2pGdHBRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  # Step 1a: Configure SSL with the certificate and private key
  # ...
  # Step 1a: End of SSL configuration

server:
  port: 8443
  ssl:
    bundle: web
  # Step 1b: Enable SSL and specify ssl bundle
  # ...
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie: 
        same-site: strict
  # Step 5: End of session cookie configuration
