---
name: security

on:
  workflow_dispatch:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  osv-scanner:
    name: run osv-scanner
    uses: google/osv-scanner-action/osv-scanner-action@c51854704019a247608d928f370c98740469d4b5
    with:
      scan-args: |-
        --format sarif
        --output DependenciesAnalysisFull.sarif
        ./
    continue-on-error: true

  semgrep:
    name: run semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:aba64aaf601ff71b769b082d3c9f95cb02a2bb20a6404f42ae94f240aec6ace7
