---
name: security

on:
 workflow_dispatch

permissions:
 # Required to upload SARIF file to CodeQL.
 actions: read
 # Require writing security events to upload SARIF file
 security-events: write
 # to fetch code (actions/checkout)
 contents: read

name: run osv-scanner
  uses: google/osv-scanner-action/osv-scanner-action@<SHA256>
  with:
    scan-args: |-
      --format sarif
      --output DependenciesAnalysisFull.sarif
      ./
  continue-on-error: true

runs-on: ubuntu-latest
container:
 image: returntocorp/semgrep@<HASH>
